apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: goods-price-service-pipeline
  namespace: goods-price-ci
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      default: "https://github.com/RizkiRachman/goods-price-comparison-service.git"
    - name: git-revision
      type: string
      default: "main"
    - name: image-name
      type: string
      default: "goods-price-comparison-service"
    - name: registry
      type: string
      default: "localhost:5000"
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
    - name: build
      taskRef:
        name: maven-build
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-cache
          workspace: shared-workspace
      params:
        - name: GOALS
          value: "clean package -DskipTests"
    - name: docker-build
      taskRef:
        name: docker-build
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "$(params.image-name):$(context.pipelineRun.name)"
        - name: REGISTRY
          value: "$(params.registry)"
    - name: deploy
      taskRef:
        name: deploy-app
      runAfter:
        - docker-build
      params:
        - name: IMAGE
          value: "$(params.registry)/$(params.image-name):$(context.pipelineRun.name)"
        - name: NAMESPACE
          value: "goods-price-ci"
