# Kind cluster config with insecure registry support
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.89.0.2:32242"]
      endpoint = ["http://10.89.0.2:32242"]
  - |
    [plugins."io.containerd.grpc.v1.cri".registry.configs."10.89.0.2:32242".tls]
      insecure_skip_verify = true
