apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goods-price-ci

resources:
  # Tasks
  - 01-tasks/git-clone.yaml
  - 01-tasks/maven-build.yaml
  - 01-tasks/maven-test.yaml
  - 01-tasks/kaniko-build.yaml
  - 01-tasks/podman-push.yaml
  - 01-tasks/docker-build-quay.yaml
  - 01-tasks/deploy.yaml
  - 01-tasks/deploy-from-registry.yaml
  # Pipelines
  - pipeline.yaml
  - pipeline-quay.yaml
  - pipeline-deploy-only.yaml
  # PipelineRuns (example triggers)
  - pipeline-run.yaml
  - pipeline-run-quay.yaml
