# PersistentVolumeClaim for Maven cache
# This PVC is used by the maven-build Task to cache dependencies
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache-pvc
  namespace: goods-price-ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
