# =============================================
# Actuator
# =============================================

# Expose all actuator endpoints
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# Prometheus endpoint
management.endpoint.prometheus.enabled=true

# Health details
management.endpoint.health.show-details=when-authorized

# Info endpoint
management.info.env.enabled=true
