apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goods-price-ci

resources:
  - namespace.yaml      # 01 - Create namespace first
  - registry.yaml       # 02 - Local Docker registry
  - deployment.yaml     # 03 - App deployment manifest
  - service.yaml        # 04 - App service
