apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${PIPELINE_SERVICE_ACCOUNT}
  namespace: ${PIPELINE_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${PIPELINE_SERVICE_ACCOUNT}-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "taskruns", "pipelines", "pipelineruns", "pipelineresources"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${PIPELINE_SERVICE_ACCOUNT}-binding
subjects:
  - kind: ServiceAccount
    name: ${PIPELINE_SERVICE_ACCOUNT}
    namespace: ${PIPELINE_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: ${PIPELINE_SERVICE_ACCOUNT}-role
  apiGroup: rbac.authorization.k8s.io
