CREATE TABLE products (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)    NOT NULL,
    category    VARCHAR(255),
    unit        VARCHAR(255),
    created_at  TIMESTAMP       NOT NULL,
    updated_at  TIMESTAMP       NOT NULL
);
