CREATE TABLE prices (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT          NOT NULL,
    store_id        BIGINT          NOT NULL,
    price           DOUBLE PRECISION NOT NULL,
    unit_price      DOUBLE PRECISION,
    date_recorded   DATE            NOT NULL,
    is_promo        BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL
);

ALTER TABLE prices ADD CONSTRAINT fk_prices_product FOREIGN KEY (product_id) REFERENCES products (id);
ALTER TABLE prices ADD CONSTRAINT fk_prices_store FOREIGN KEY (store_id) REFERENCES stores (id);

CREATE INDEX idx_prices_product_id ON prices (product_id);
CREATE INDEX idx_prices_store_id   ON prices (store_id);
CREATE INDEX idx_prices_date        ON prices (date_recorded);
