CREATE TABLE receipt_items (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id      UUID            NOT NULL,
    product_name    VARCHAR(255)    NOT NULL,
    category        VARCHAR(255),
    quantity        DOUBLE PRECISION,
    unit_price      DOUBLE PRECISION,
    total_price     DOUBLE PRECISION,
    unit            VARCHAR(255)
);

ALTER TABLE receipt_items
    ADD CONSTRAINT fk_receipt_items_receipt FOREIGN KEY (receipt_id) REFERENCES receipts (id);

CREATE INDEX idx_receipt_items_receipt_id ON receipt_items (receipt_id);
