# PipelineRun: Execute the goods-price-service pipeline
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ${DEPLOYMENT_NAME}-
  namespace: ${PIPELINE_NAMESPACE}
spec:
  pipelineRef:
    name: goods-price-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: ${DEPLOYMENT_NAME}-pvc
  params:
    - name: git-url
      value: ${GIT_REPO_URL}
    - name: git-revision
      value: ${GIT_REPO_DEFAULT_BRANCH}
    - name: image-name
      value: ${IMAGE_NAME}
    - name: image-tag
      value: ${IMAGE_TAG}
    - name: registry-host
      value: ${REGISTRY_KIND_HOST}
    - name: registry-port
      value: ${REGISTRY_PORT}
    - name: test-goals
      value: "test"
    - name: deployment-namespace
      value: ${DEPLOYMENT_NAMESPACE}
    - name: deployment-name
      value: ${DEPLOYMENT_NAME}
